pilots = {
    "pilot_1": {"pilot_id": 1, "name": "charles lindbergh"},
    "pilot_2": {"pilot_id": 2, "name": "amelia earhart"},
    "pilot_3": {"pilot_id": 3, "name": "wilbur wright"},
    "pilot_4": {"pilot_id": 4, "name": "orville wright"},
    "pilot_5": {"pilot_id": 5, "name": "jacqueline auriol"},
    "pilot_6": {"pilot_id": 6, "name": "chuck yeager"},
    "pilot_7": {"pilot_id": 7, "name": "neil armstrong"},
    "pilot_8": {"pilot_id": 8, "name": "buzz aldrin"},
    "pilot_9": {"pilot_id": 9, "name": "william knight"},
    "pilot_10": {"pilot_id": 10, "name": "sally ride"},
    "pilot_11": {"pilot_id": 11, "name": "eileen collins"},
    "pilot_12": {"pilot_id": 12, "name": "yuri gagarin"},
    "pilot_13": {"pilot_id": 13, "name": "jean batten"},
    "pilot_14": {"pilot_id": 14, "name": "beryl markham"},
    "pilot_15": {"pilot_id": 15, "name": "maverick"},
    "pilot_16": {"pilot_id": 16, "name": "goose"},
    "pilot_17": {"pilot_id": 17, "name": "iceman"},
}


destinations = {
    "destination_1": {"destination_id": 1, "destination_name": "tokyo"},
    "destination_2": {"destination_id": 2, "destination_name": "paris"},
    "destination_3": {"destination_id": 3, "destination_name": "new york"},
    "destination_4": {"destination_id": 4, "destination_name": "rome"},
    "destination_5": {"destination_id": 5, "destination_name": "amsterdam"},
    "destination_6": {"destination_id": 6, "destination_name": "dubai"},
    "destination_7": {"destination_id": 7, "destination_name": "london"},
    "destination_8": {"destination_id": 8, "destination_name": "singapore"},
    "destination_9": {"destination_id": 9, "destination_name": "barcelona"},
    "destination_10": {"destination_id": 10, "destination_name": "istanbul"},
    "destination_11": {"destination_id": 11, "destination_name": "berlin"},
    "destination_12": {"destination_id": 12, "destination_name": "sydney"},
    "destination_13": {"destination_id": 13, "destination_name": "delhi"},
    "destination_14": {"destination_id": 14, "destination_name": "beijing"},
    "destination_15": {"destination_id": 15, "destination_name": "wellington"},
}


flights = {
    "flight_1": {
        "flight_id": 1,
        "departure_date": "2025-04-01",
        "departure_time": "08:00:00",
        "status": "completed",
        "destination_id": 1,
    },
    "flight_2": {
        "flight_id": 2,
        "departure_date": "2025-04-01",
        "departure_time": "11:45:00",
        "status": "completed",
        "destination_id": 2,
    },
    "flight_3": {
        "flight_id": 3,
        "departure_date": "2025-04-01",
        "departure_time": "14:30:00",
        "status": "completed",
        "destination_id": 3,
    },
    "flight_4": {
        "flight_id": 4,
        "departure_date": "2025-04-02",
        "departure_time": "06:15:00",
        "status": "completed",
        "destination_id": 4,
    },
    "flight_5": {
        "flight_id": 5,
        "departure_date": "2025-04-02",
        "departure_time": "12:00:00",
        "status": "completed",
        "destination_id": 5,
    },
    "flight_6": {
        "flight_id": 6,
        "departure_date": "2025-04-03",
        "departure_time": "09:30:00",
        "status": "arrived",
        "destination_id": 6,
    },
    "flight_7": {
        "flight_id": 7,
        "departure_date": "2025-04-03",
        "departure_time": "15:45:00",
        "status": "arrived",
        "destination_id": 3,
    },
    "flight_8": {
        "flight_id": 8,
        "departure_date": "2025-04-04",
        "departure_time": "07:00:00",
        "status": "arrived",
        "destination_id": 7,
    },
    "flight_9": {
        "flight_id": 9,
        "departure_date": "2025-05-05",
        "departure_time": "13:20:00",
        "status": "delayed",
        "destination_id": 8,
    },
    "flight_10": {
        "flight_id": 10,
        "departure_date": "2025-05-06",
        "departure_time": "10:10:00",
        "status": "cancelled",
        "destination_id": 9,
    },
    "flight_11": {
        "flight_id": 11,
        "departure_date": "2025-05-06",
        "departure_time": "17:30:00",
        "status": "on time",
        "destination_id": 2,
    },
    "flight_12": {
        "flight_id": 12,
        "departure_date": "2025-05-07",
        "departure_time": "09:00:00",
        "status": "on time",
        "destination_id": 10,
    },
    "flight_13": {
        "flight_id": 13,
        "departure_date": "2025-05-07",
        "departure_time": "19:15:00",
        "status": "delayed",
        "destination_id": 11,
    },
    "flight_14": {
        "flight_id": 14,
        "departure_date": "2025-05-08",
        "departure_time": "08:45:00",
        "status": "scheduled",
        "destination_id": 12,
    },
    "flight_15": {
        "flight_id": 15,
        "departure_date": "2025-05-08",
        "departure_time": "18:00:00",
        "status": "scheduled",
        "destination_id": 1,
    },
}


flight_pilot_assignments = {
    "assignment_1": {"flight_id": 1, "pilot_id": 1},
    "assignment_2": {"flight_id": 1, "pilot_id": 2},
    "assignment_3": {"flight_id": 2, "pilot_id": 3},
    "assignment_4": {"flight_id": 2, "pilot_id": 4},
    "assignment_6": {"flight_id": 3, "pilot_id": 5},
    "assignment_7": {"flight_id": 3, "pilot_id": 6},
    "assignment_8": {"flight_id": 4, "pilot_id": 7},
    "assignment_9": {"flight_id": 4, "pilot_id": 8},
    "assignment_10": {"flight_id": 4, "pilot_id": 9},
    "assignment_11": {"flight_id": 5, "pilot_id": 10},
    "assignment_12": {"flight_id": 5, "pilot_id": 11},
    "assignment_13": {"flight_id": 5, "pilot_id": 2},
    "assignment_14": {"flight_id": 6, "pilot_id": 3},
    "assignment_15": {"flight_id": 6, "pilot_id": 4},
    "assignment_16": {"flight_id": 7, "pilot_id": 5},
    "assignment_17": {"flight_id": 7, "pilot_id": 6},
    "assignment_18": {"flight_id": 8, "pilot_id": 7},
    "assignment_19": {"flight_id": 8, "pilot_id": 8},
    "assignment_20": {"flight_id": 9, "pilot_id": 9},
    "assignment_21": {"flight_id": 9, "pilot_id": 10},
    "assignment_22": {"flight_id": 10, "pilot_id": 11},
    "assignment_23": {"flight_id": 10, "pilot_id": 2},
    "assignment_24": {"flight_id": 11, "pilot_id": 3},
    "assignment_25": {"flight_id": 11, "pilot_id": 4},
    "assignment_26": {"flight_id": 11, "pilot_id": 5},
    "assignment_27": {"flight_id": 11, "pilot_id": 6},
    "assignment_28": {"flight_id": 12, "pilot_id": 7},
    "assignment_29": {"flight_id": 12, "pilot_id": 8},
    "assignment_30": {"flight_id": 13, "pilot_id": 9},
    "assignment_31": {"flight_id": 13, "pilot_id": 10},
    "assignment_32": {"flight_id": 14, "pilot_id": 11},
    "assignment_33": {"flight_id": 14, "pilot_id": 2},
    "assignment_34": {"flight_id": 15, "pilot_id": 3},
    "assignment_35": {"flight_id": 15, "pilot_id": 4},
}
